name = "WendaoCodeParser"
uuid = "f20f04df-04eb-4b3b-9fa2-a7e4ac8e000b"
version = "0.1.0"
authors = ["CyberXiuXian Workshop"]

[deps]
Absyn = "ce2f92e2-a952-11e9-0543-8b443f216f1d"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
ArrowTypes = "31f734f8-188a-4ce0-8406-c8a06bd891cd"
ImmutableList = "4a558cac-c1ed-11e9-20da-3584bcd8709a"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaModelica = "9d7f2a79-07b5-5542-8b19-c0100dda6b06"
OMParser = "11f87224-cae7-4e99-a924-e50d12f62c59"
PureHTTP2 = "7d1e1b98-28e7-4969-8df9-5a308937986a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WendaoArrow = "561c8d8d-4bcf-4807-873b-a6b7d1e55843"

[sources]
Absyn = {rev = "master", url = "https://github.com/OpenModelica/Absyn.jl"}
Arrow = {rev = "2ec9e65ef648c5da4060f0ef8b8e78e7ed00226d", url = "https://github.com/JuliaCN/arrow-julia.git"}
ArrowTypes = {rev = "2ec9e65ef648c5da4060f0ef8b8e78e7ed00226d", subdir = "src/ArrowTypes", url = "https://github.com/JuliaCN/arrow-julia.git"}
ImmutableList = {rev = "master", url = "https://github.com/OpenModelica/ImmutableList.jl"}
JuliaSyntax = {rev = "main", url = "https://github.com/JuliaLang/JuliaSyntax.jl"}
MetaModelica = {rev = "master", url = "https://github.com/OpenModelica/MetaModelica.jl"}
OMParser = {rev = "d59051069e43fb2624aa13fe8935532ca15aecec", url = "https://github.com/tao3k/OMParser.jl"}
PureHTTP2 = {rev = "03d8853e9556a4355d7b650853cda62b1906d88e", url = "https://github.com/s-celles/PureHTTP2.jl"}
WendaoArrow = {rev = "308c9fb1864af132eb1942b6cca0c5c1403e8ca8", url = "https://github.com/tao3k/WendaoArrow.jl.git"}

[compat]
Absyn = "1.3"
Arrow = "2.8.1"
ArrowTypes = "2.3.0"
ImmutableList = "0.1"
JuliaSyntax = "2"
MetaModelica = "0.0.5"
OMParser = "0.0.3"
PureHTTP2 = "0.5.0"
Tables = "1"
WendaoArrow = "0.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
